// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqwsumdtodmnbcagqtmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxd3N1bWR0b2RtbmJjYWdxdG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjE0NDYsImV4cCI6MjA2NTYzNzQ0Nn0.JZe3RGHUTMN6dw2RjtiU6m5b6qtAws6TiYKsMysBXOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);